name: chat
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis: 
    image: redis:latest
    container_name: chat-invite-redis
    ports: 
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped


volumes:
  postgres_data:
  redis-data: 
    driver: local